name: QMK Firmware Build

on:
  push:
    branches:
      - main   # 任意のブランチ名に変更可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QMK
        run: |
          python3 -m pip install --upgrade pip
          pip3 install qmk

      - name: Compile firmware
        run: |
          qmk setup -y
          qmk compile -kb keyball/keyball44 -km mykeymap_LED_layer   # ←キーボード名・キーマップ名を指定

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .build/*.hex
